
include(NCPP/SetGlobal)

NCPP_SetGlobal(NCPP_VERSION_MAJOR 0)
NCPP_SetGlobal(NCPP_VERSION_MINOR 2)
NCPP_SetGlobal(NCPP_VERSION_PATCH 0)

NCPP_SetGlobal(NCPP_MAX_VERSION_COMPONENT_VALUE 99)
math(EXPR NCPP_VERSION_NUMBER "${NCPP_VERSION_MAJOR} * (${NCPP_MAX_VERSION_COMPONENT_VALUE} + 1)^2 + ${NCPP_VERSION_MINOR} * (${NCPP_MAX_VERSION_COMPONENT_VALUE} + 1) + ${NCPP_VERSION_PATCH}")

NCPP_SetGlobal(NCPP_VERSION ${NCPP_VERSION_MAJOR}.${NCPP_VERSION_MINOR}.${NCPP_VERSION_PATCH})
NCPP_SetGlobal(ncpp_VERSION ${NCPP_VERSION})

NCPP_SetGlobal(NCPP_VERSION_WITH_UNDERSCORE ${NCPP_VERSION_MAJOR}_${NCPP_VERSION_MINOR}_${NCPP_VERSION_PATCH})

NCPP_SetGlobal(NCPP_VERSION_${NCPP_VERSION_WITH_UNDERSCORE} "")