
set(NCPP_VERSION_MAJOR 0)
set(NCPP_VERSION_MINOR 2)
set(NCPP_VERSION_PATCH 0)

set(NCPP_MAX_VERSION_COMPONENT_VALUE 99)
math(EXPR NCPP_VERSION_NUMBER "${NCPP_VERSION_MAJOR} * (${NCPP_MAX_VERSION_COMPONENT_VALUE} + 1)^2 + ${NCPP_VERSION_MINOR} * (${NCPP_MAX_VERSION_COMPONENT_VALUE} + 1) + ${NCPP_VERSION_PATCH}")

set(NCPP_VERSION ${NCPP_VERSION_MAJOR}.${NCPP_VERSION_MINOR}.${NCPP_VERSION_PATCH})
set(ncpp_VERSION ${NCPP_VERSION})

set(NCPP_VERSION_WITH_UNDERSCORE ${NCPP_VERSION_MAJOR}_${NCPP_VERSION_MINOR}_${NCPP_VERSION_PATCH})

set(NCPP_VERSION_${NCPP_VERSION_WITH_UNDERSCORE})