
#pragma once

/** @file ncpp/config_macros.hpp
*	@brief Contains config macro documentations.
 * 	@details Mustn't include this header.
*/

static_assert("Mustn't include this header");



#define NCPP_DEFAULT_ALIGN //

#define NCPP_ENABLE_NATIVE_MEMORY_COUNTING //
#define NCPP_DEFAULT_TAGGED_HEAP_CAPACITY //
#define NCPP_DEFAULT_TAGGED_HEAP_BLOCK_CAPACITY //
#define NCPP_DEFAULT_TAGGED_HEAP_MIN_BLOCK_COUNT_PER_CATEGORY //
#define NCPP_DEFAULT_ALLOCATOR_TEMPLATE //
#define NCPP_DEFAULT_STACK_CAPACITY //
#define NCPP_DEFAULT_STACK_COUNT_PER_CHUNK //
#define NCPP_DEFAULT_STACK_HEAP_MIN_CHUNK_COUNT //
#define NCPP_DEFAULT_MAX_OBJECT_COUNT_PER_POOL //
#define NCPP_DEFAULT_POOL_COUNT_PER_CHUNK //
#define NCPP_DEFAULT_POOL_HEAP_MIN_CHUNK_COUNT //

#define NCPP_DEFAULT_HANDLE_MAP_RESERVE_COUNT //
#define NCPP_DEFAULT_HANDLE_MAP_VECTOR_RESERVE_COUNT //

#define NCPP_ENABLE_FIBER //
#define NCPP_DEFAULT_THREAD_STACK_SIZE //
#define NCPP_DEFAULT_FIBER_STACK_SIZE //
#define NCPP_ENABLE_WEAKLOCK_WARNING //

#define NCPP_DEFAULT_JOB_HANDLE_QUEUE_CAPACITY //
#define NCPP_DEFAULT_JOB_INSTANCE_POOL_CAPACITY //